### ISSUE TITLE
ikoner når man bruker komponenter

### ISSUE THREAD

**Issue by cappaul** [Skatteetaten/frontend-components#3]
jeg har et issue med at ikonene ikke blir vist når man copy paster koden til frontend komponentene

Bilde av app:
-----------------------------------------------------------------------------------------------------------
![Screenshot from 211-24 12-42-05](https://user-images.githubusercontent.com/70642710/100090476-84328a00-2e53-11eb-99f8-555ed7ade56a.png)

Bilde av koden jeg hentet inn:
-------------------------------------------------------------------------------------------------------------
![Screenshot fr11-24 12-42-10](https://user-images.githubusercontent.com/70642710/100090496-898fd480-2e53-11eb-8443-7f9cc15cd548.png)
-------------------------------------------------------------------------------------------------------------
dette gjelder alle komponentene jeg har prøvd

**Comment by cappaul** [comment]
jeg har også fulgt 'kom igang'

import React from 'react';
import ReactDOM from 'react-dom';
import SkeBasis from '@skatteetaten/frontend-components/SkeBasis';
import App from './App';

ReactDOM.render(
  <SkeBasis>
    <App />
  </SkeBasis>,
  document.getElementById('root')
);

**Comment by eivindland** [comment]
Dette stammer sannsynligvis av at måten vi importerer ikonfonten på ikke er kompatibel med react-scripts versjon 4.0. Vi jobber med saken, men foreløpig fiks kan være å bruke react-scripts versjon 3.4.

**Comment by cappaul** [comment]
det fungerer
